
development:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: purchasing
  pool: 5
  username: root
  password: root

test:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: purchasing_test
  pool: 5
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: purchasing
  pool: 5
  username: root
  password: root

