
development:
  adapter: postgresql
  encoding: unicode
  database: purchasing
  pool: 5
  port: 5000
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: purchasing_test
  pool: 5
  port: 5000
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: purchasing
  pool: 5
  port: 5000
  username: postgres
  password:
