cas:
  #url: "http://localhost:443"
  url: "https://login.biola.edu/cas"

urn_namespaces:
  - "urn:biola:apps:all:"

app:
  name: &app_name Purchasing
  pagination:
    per_page: 15
    show_first: false
    show_last: false
  tax_rate: .1
  tax_codes: ['%0.0', '%10.0', '%9.75', '%9.5', '%9.25', '%9.0', '%8.75', '%8.5', '%8.25', '%8.0']

  tabs:
    New
    Pending
    Purchased
    Reconciled
    Cancelled
    Starred

email:
  smtp:
    server:

local_urls:
  wicked_pdf: 'c:\wkhtmltopdf\wkhtmltopdf.exe'

Rack:
  disabled:
    true
