cas:
  #url: "http://localhost:443"
  url: "https://login.biola.edu/cas"

urn_namespaces:
  - "urn:biola:apps:central-stores:"

app:
  name: &app_name Purchasing
  pagination:
    per_page: 15
    show_first: false
    show_last: false
  tax_rate: .1
  tabs:
    Pending
    Received
    Reconciled

ui:
  menu:
  - controller: purchases
    icon: icon-shopping-cart

  - controller: users
    remote: true
    icon: icon-user

  - controller: vendors
    icon: icon-home

  - controller: tags # Only admin
    remote: true
    icon: icon-tag

  - url: /settings
    text: Settings
    remote: true
    icon: icon-cogs

  - url: /reports
    text: Reports
    icon: icon-folder-open-alt

  - url: /logout
    text: Logout
    icon: icon-signout
