cas:
  #url: "http://localhost:443"
  url: "https://login.biola.edu/cas"

urn_namespaces:
  - "urn:biola:apps:all:"

app:
  name: &app_name Purchasing
  pagination:
    per_page: 15
    show_first: false
    show_last: false
  tax_rate: .1
  tax_codes: ['%0.0', '%10.0', '%9.75', '%9.5', '%9.25', '%9.0', '%8.75', '%8.5', '%8.25', '%8.0']

  tabs:
    Pending
    Reconciled
    Cancelled


ui:
  menu:
  - controller: purchases
    icon: fa-shopping-cart

  - controller: users
    icon: fa-user

  - controller: vendors
    icon: fa-home

  - controller: tags # Only admin
    modal: true
    icon: fa-tags

  - url: settings
    text: Settings
    modal: true
    icon: fa-cogs

  - url: reports
    text: Reports
    modal: true
    icon: fa-folder-open-o

  - url: logout
    text: Logout
    icon: fa-sign-out
