cas:
  #url: "http://localhost:443"
  url: "https://login.biola.edu/cas"

urn_namespaces:
  - "urn:biola:apps:all:"

app:
  name: &app_name Purchasing
  pagination:
    per_page: 15
    show_first: false
    show_last: false
  tax_rate: .1
  tax_codes: ['%0.0', '%10.0', '%9.75', '%9.5', '%9.25', '%9.0', '%8.75', '%8.5', '%8.25', '%8.0']

  tabs:
    New
    Pending
    Reconciled
    Cancelled


ui:
  menu:
  - type: link_to
    url: purchases
    controller: purchases
    icon: fa-shopping-cart

  - type: link_to
    url: users
    controller: users
    icon: fa-user

  - type: link_to
    url: vendors
    controller: vendors
    icon: fa-home

  - type: action
    url: tags # Only admin
    controller: tags
    icon: fa-tags

  - type: action
    url: settings
    icon: fa-cogs

  - type: action
    url: reports
    icon: fa-folder-open-o

  - type: url
    url: logout
    icon: fa-sign-out
